# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEAki2bsY3bBZhKXdPvWFTb_X06qFNKF
"""

# ========== Imports & Config ==========
import numpy as np
import pandas as pd
import joblib
import streamlit as st

model = joblib.load("productivity_model.pkl")
le = joblib.load("label_encoder.pkl")

def predict_productivity(input_data: dict):
    df = pd.DataFrame([input_data])   # single-row DataFrame
    prediction = model.predict(df)
    label = le.inverse_transform(prediction)[0]
    return label

# Example usage
new_person = {
    "age": 29,
    "work_hours_per_day": 8,
    "sleep_hours": 6,
    "perceived_productivity_score": 7,
    "job_satisfaction_score": 8
}
print("Predicted Productivity:", predict_productivity(new_person))

st.title("Productivity Prediction")

age = st.number_input("Age", 18, 60, 25)
work_hours = st.slider("Work Hours Per Day", 0, 12, 8)
sleep = st.slider("Sleep Hours", 0, 12, 6)
perceived = st.slider("Perceived Productivity Score (1-10)", 1, 10, 7)
satisfaction = st.slider("Job Satisfaction Score (1-10)", 1, 10, 8)

if st.button("Predict"):
    data = {
        "age": age,
        "work_hours_per_day": work_hours,
        "sleep_hours": sleep,
        "perceived_productivity_score": perceived,
        "job_satisfaction_score": satisfaction
    }
    result = predict_productivity(data)
    st.success(f"Predicted Productivity: {result}")